### ISSUE TITLE
No line numbers?

### ISSUE THREAD

**Issue by avimar** [forthright/vile-synt#1]
```
synt:
  config:
    similarity: 70
    ngram: 1
    minlength: 10
    estype: "module"
```

I upgraded to similarity of 80 and length of 100. 

Yet, I got a bunch of matches like this:

```
warn duplicate test/callRouting.js: Similar code in test/callRouting.js (vile-synt)
warn duplicate myNumbers/myNumbers.js: Similar code in myNumbers/myNumbers.js, speedDials/speedDials.js (vile-synt)
```

So we have matches to self, and matches to another file too. But no line numbers mentioned.
How do I make use of this?
